main: com.cavetale.buildmything.BuildMyThingPlugin
name: BuildMyThing

version: ${version}
api-version: '1.21'

author: StarTux
website: https://github.com/StarTux/BuildMyThing
description: BuildMyThing Plugin

depend:
- Core
- VoidGenerator
- Creative
- Fam

softdepend: []

commands:

  buildmything:
    aliases: [bmt]
    description: BuildMyThing Command
    permission: buildmything.buildmything
    usage: |-
      /buildmything

  buildmythingadmin:
    aliases: [bmtadm]
    description: BuildMyThing Admin Command
    permission: buildmything.admin
    usage: |-
      /buildmythingadmin

permissions:

  buildmything.buildmything:
    description: Use /buildmything
    default: op

  buildmything.admin:
    description: Use /buildmythingadmin
    default: op
